export const ROUTES = {
  root: "/",
  login: "/login",
  register: "/register",
  home: "/home",
  user: "/user",
  settings: "/settings",
  settingsDataEntry: "/settings/data-entry",
  settingsDataEntryVoucher: "/settings/data-entry/voucher-settings",
  settingsDataEntryOrder: "/settings/data-entry/order-settings",
  settingsDataEntryReceipt: "/settings/data-entry/receipt-settings",
  settingsVoucher: "/settings/data-entry/voucher",
  settingsVoucherSeries: "/settings/data-entry/voucher/series",
  settingsVoucherSeriesList: "/settings/data-entry/voucher/series/list",
  settingsVoucherSeriesCreate: "/settings/data-entry/voucher/series/create",
  settingsPrintConfigurations: "/settings/print-configurations",
  settingsPrintConfigurationsSaleOrder:
    "/settings/print-configurations/sale-order",
  settingsPrintConfigurationsReceipt:
    "/settings/print-configurations/receipt",

  outstanding: "/outstanding",
  outstandingPartyDetail: "/outstanding/party/:partyId",
  daybook: "/daybook",
  stockRegister: "/stock-register",
  CashBankBalancePage: "/cash-bank",
  createOrder: "/create-order",
  transactionDetail: "/transactions/:voucherType/:voucherId",
  saleOrderDetail: "/sale-orders/:saleOrderId",
  saleOrderEdit: "/sale-orders/:id/edit",
  salesSelectItems: "/sales/create/select-items",
  createReceipt: "/create-receipt",
  mastersUserRegister: "/users/create",
  mastersUsers: "/users/list",
  masters: "/masters",
  mastersCompany: "/masters/company",
  mastersCompanyRegister: "/masters/company/register",
  mastersCustomers: "/masters/customers",
  mastersProducts: "/masters/products",
  mastersPartyList: "/masters/party/list",
  mastersPartyRegister: "/masters/party/register",
  BankBalanceListPage: "/bank-balance",
  CashInHandListPage: "/cash-in-hand",
};

export const MASTER_ROUTE_REDIRECTS = {
  company: ROUTES.mastersCompany,
  companyRegister: ROUTES.mastersCompanyRegister,
  users: ROUTES.mastersUsers,
  userRegister: ROUTES.mastersUserRegister,
  customers: ROUTES.mastersCustomers,
  products: ROUTES.mastersProducts,
  partyList: ROUTES.mastersPartyList,
  partyRegister: ROUTES.mastersPartyRegister,
};
