export const countries = [
  {
    countryName: "India",
    currency: "INR",
    currencyName: "Rupee",
    subunit: "Paisa",
    symbol: "₹",
    timeZone: "Asia/Kolkata",
  },
  {
    countryName: "Saudi Arabia",
    currency: "SAR",
    currencyName: "Riyal",
    subunit: "Halala",
    symbol: "ر.س",
    timeZone: "Asia/Riyadh",
  },
  {
    countryName: "United Arab Emirates",
    currency: "AED",
    currencyName: "Dirham",
    subunit: "Fils",
    symbol: "د.إ",
    timeZone: "Asia/Dubai",
  },
  {
    countryName: "Iraq",
    currency: "IQD",
    currencyName: "Dinar",
    subunit: "Fils",
    symbol: "د.ع",
    timeZone: "Asia/Baghdad",
  },
  {
    countryName: "Iran",
    currency: "IRR",
    currencyName: "Rial",
    subunit: "Dinar",
    symbol: "﷼",
    timeZone: "Asia/Tehran",
  },
  {
    countryName: "Jordan",
    currency: "JOD",
    currencyName: "Dinar",
    subunit: "Piastre",
    symbol: "د.أ",
    timeZone: "Asia/Amman",
  },
  {
    countryName: "Lebanon",
    currency: "LBP",
    currencyName: "Pound",
    subunit: "Piastre",
    symbol: "ل.ل",
    timeZone: "Asia/Beirut",
  },
  {
    countryName: "Syria",
    currency: "SYP",
    currencyName: "Pound",
    subunit: "Piastre",
    symbol: "س.س",
    timeZone: "Asia/Damascus",
  },
  {
    countryName: "Israel",
    currency: "ILS",
    currencyName: "Shekel",
    subunit: "Agorot",
    symbol: "₪",
    timeZone: "Asia/Jerusalem",
  },
  {
    countryName: "Palestine",
    currency: "ILS",
    currencyName: "Shekel",
    subunit: "Agorot",
    symbol: "₪",
    timeZone: "Asia/Gaza",
  },
  {
    countryName: "Kuwait",
    currency: "KWD",
    currencyName: "Dinar",
    subunit: "Fils",
    symbol: "د.ك",
    timeZone: "Asia/Kuwait",
  },
  {
    countryName: "Qatar",
    currency: "QAR",
    currencyName: "Riyal",
    subunit: "Dirham",
    symbol: "ر.ق",
    timeZone: "Asia/Qatar",
  },
  {
    countryName: "Oman",
    currency: "OMR",
    currencyName: "Rial",
    subunit: "Baisa",
    symbol: "ر.ع",
    timeZone: "Asia/Muscat",
  },
  {
    countryName: "Bahrain",
    currency: "BHD",
    currencyName: "Dinar",
    subunit: "Fils",
    symbol: ".د.ب",
    timeZone: "Asia/Bahrain",
  },
  {
    countryName: "Yemen",
    currency: "YER",
    currencyName: "Rial",
    subunit: "Baisa",
    symbol: "ر.ي",
    timeZone: "Asia/Aden",
  },
];

export const INDIA_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];


