// src/constants/industries.js
export const INDUSTRIES = [
  "Wholesale Trading",
  "Retail Trading",
  "Import & Export",
  "Distribution / Dealers",
  "E-commerce / Online Trading",
  "IT Services",
  "Web Design & Development",
  "Cyber Security Services",
  "Hardware & Networking",
  "Construction Companies",
  "Pharmaceutical Manufacturing",
  "Food Manufacturing",
  "Textile / Garment Manufacturing",
  "Chemical Manufacturing",
  "Plastic Manufacturing",
  "Steel / Metal Manufacturing",
  "Furniture Manufacturing",
  "Building Contractors",
  "Real Estate Developers",
  "Electrical Equipment Manufacturing",
  "Electronics Manufacturing",
  "Automobile Manufacturing",
  "Hospitals",
  "Clinics",
  "Medical Laboratories",
  "Medical Equipment Suppliers",
  "Pharmacies / Medical Stores",
  "Interior Design",
  "Vehicle Dealers",
  "Automobile Service Centres",
  "Insurance Companies",
  "Chartered Accountants / Audit Firms",
  "Tax Consultants",
  "Schools",
  "Colleges",
  "Training Institutes",
  "Coaching Centers",
  "Educational Consultants",
  "Software Development",
  "Restaurants / Cafes",
  "Travel Agencies",
  "Tourism Operators",
  "Advertising & Marketing Agencies",
  "Event Management",
  "Security Services",
  "Cleaning / Facility Management",
  "NGOs / Non-Profit Organizations",
  "Government Organizations",
  "Property Management",
  "Spare Parts Dealers",
  "Transport & Logistics",
  "Banks",
  "Finance Companies",
  "Hotels & Resorts",
];
